### ISSUE TITLE
spring cloud

### ISSUE THREAD

**Issue by chengbinbbs** [lupindong/xq_seckill_microservice#1]
你好，请问这个分布式配置中心config是不是没有配置完整，另外能否请教一下`eureka.client.serviceUrl.defaultZone= http://platform:p1atf0rmds*lovexq.NET@peer1:8001/eureka`,注册中心这段配置里面主机peer1前面platform:p1atf0rmds*lovexq.NET@是什么用处？

**Comment by lupindong** [comment]
抱歉啊，是不完整的，因为里面配置了一些不便公开的账号密码，所以后面我删掉了。。。"platform:p1atf0rmds*lovexq.NET"这个是eurekal的application.yml配置的security的账号和密码，用于限制对eurekal的访问。

**Comment by lupindong** [comment]
@chengbinbbs 抱歉啊，是不完整的，因为里面配置了一些不便公开的账号密码，所以后面我删掉了。。。"platform:p1atf0rmds*lovexq.NET"这个是eurekal的application.yml配置的security的账号和密码，用于限制对eurekal的访问。

**Comment by chengbinbbs** [comment]
config可以指向本地或者git服务器，自己配一下就ok了，哈哈。security的账号和密码配置：
security:
  basic:
    enabled: true
  user:
    name: platform
    password: p1atf0rmds*lovexq.NET
这样应该就可以了吧，写在http://platform:p1atf0rmds*lovexq.NET@eureka1:8001/eureka里面，好像没有见过这种写法，eureka是怎么识别的呢？还有想问一下你的秒杀的逻辑，秒杀的详情页，是用模板生成的，你们一般什么时候去生成呢?看你们好像是调接口/specials手动生成的，你们秒杀在生产中式如何实施的呢？请教一下

**Comment by lupindong** [comment]
@chengbinbbs 让你见笑了，这个项目只是当初我学习spring cloud的练手之作，很多逻辑都是不完善的。我司目前还是用dubbo。。。

**Comment by chengbinbbs** [comment]
@lupindong 哈哈，我们也没有实际运用，spring cloud理解还是蛮透彻的，高并发秒杀业务你很熟练，向你学习啊，你QQ多少啊?

**Comment by lupindong** [comment]
@chengbinbbs 加这个吧1156881013
